name: Send Discord Message

on:
  push:
    branches: [main]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Discord Message
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Discord Actions
        run: npm install discord-actions
      - name: Send Message
        run: |
          node index.js
          
