name: Discord Message on Push

on:
  push:
    branches:
      - main  # This triggers the action when you push to the main branch

jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: discord-actions/message@v2
        with:
          # Discord webhook URL from GitHub Secrets
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # The message you want to send to Discord
          message: "Hello this is ${{ github.actor }}: ${{ Turritopsis Dorphni Teo En Ming Time Traveller }}"
