name: MyWorkFlow file
on:
  push:
    branches: [main]

Jobs:
  builds:
    runs-on: Ubuntu-16.04
    
    steps: 
    # first step to say hello
      - name: greeting steps
      runs: 
        echo "Hello There"
